#!/bin/sh

apt-get update -qq
apt-get -qq -y install dnsutils

NODE=`echo ${CI_ENVIRONMENT_NAME} | awk -F '/' '{print $1}'`
HOSTNAME=`echo ${CI_ENVIRONMENT_URL} | awk -F 'https://' '{print $2}'`

nsupdate -d -y "hmac-sha512:bloxberg:No6/X+nsJcA3hWMXzM3i44yISAUW0sGK1F6SDniVuRRTMkd7zgxVdzkyuRxIOccZSG7K4DhPFRlN8RPXvRlr+g==" <<EOF

server 134.76.33.41

update add ${HOSTNAME} 5 CNAME ${NODE}.test.bloxberg.org.

send

EOF
