apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ${PROJECT_NAME}-${volume_name}
  name: ${PROJECT_NAME}-${volume_name}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${volume_size}
status: {}
