spec:
  template:
    spec:
      containers:
        - name: ${PROJECT_NAME}
          volumeMounts:
            - name: ${PROJECT_NAME}-${secret_name}
              mountPath: ${secret_path}
              readOnly: true
